<?php $authPrefs = ui_preferences($user ?? null); ?>
<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= htmlspecialchars($title) ?></title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/css/style.css?v=<?= filemtime(__DIR__ . '/../assets/css/style.css') ?>"></head>
<body class="auth-page theme-<?= e($authPrefs['theme']) ?> text-<?= e($authPrefs['text_scale']) ?> ui-<?= e($authPrefs['ui_scale']) ?>" data-theme="<?= e($authPrefs['theme']) ?>" data-language="<?= e($authPrefs['language']) ?>" data-text-scale="<?= e($authPrefs['text_scale']) ?>" data-ui-scale="<?= e($authPrefs['ui_scale']) ?>" data-preference-source="guest">
<main class="auth-shell">
    <a class="brand auth-brand" href="?page=home"><span class="brand-mark" aria-hidden="true"><i></i><i></i><i></i></span><span>WorkConnect</span></a>
    <section class="auth-card">
        <?php $isForgot = $page === 'forgot-password'; $isReset = $page === 'reset-password'; ?>
        <span class="auth-kicker"><?= $isForgot || $isReset ? 'Account recovery' : ($page === 'login' ? 'Welcome back' : 'Start something great') ?></span>
        <h1><?= $isForgot ? 'Reset your password' : ($isReset ? 'Choose a new password' : ($page === 'login' ? 'Sign in to WorkConnect' : 'Create your account')) ?></h1>
        <p><?= $isForgot ? 'Enter your email and we will send a secure reset link.' : ($isReset ? 'Use a strong password you have not used before.' : ($page === 'login' ? 'Continue to your projects and conversations.' : 'Join as a customer or seller.')) ?></p>
        <?php foreach (pull_flashes() as $flash): ?><div class="flash <?= e($flash['type']) ?>" role="status"><span><?= $flash['type'] === 'error' ? '!' : 'i' ?></span><p><?= e($flash['message']) ?></p></div><?php endforeach; ?>
        <form class="auth-form" action="" method="post" enctype="multipart/form-data">
            <input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>">
            <input type="hidden" name="action" value="<?= $isForgot ? 'request_password_reset' : ($isReset ? 'reset_password' : ($page === 'login' ? 'login' : 'register')) ?>">
            <?php if ($isReset): ?><input type="hidden" name="token" value="<?= e((string) ($_GET['token'] ?? '')) ?>"><?php endif; ?>
            <?php if ($page === 'register'): ?><label>Full name<input type="text" name="name" placeholder="Your full name" required></label><?php endif; ?>
            <?php if (!$isReset): ?><label>Email<input type="email" name="email" placeholder="name@example.com" required></label><?php endif; ?>
            <?php if (!$isForgot): ?><label><?= $isReset ? 'New password' : 'Password' ?><span class="password-wrap"><input id="password" type="password" name="password" placeholder="At least 8 characters" minlength="8" required><button id="toggle-password" type="button" aria-label="Show password">Show</button></span></label><?php endif; ?>
            <?php if ($isReset): ?><label>Confirm new password<input type="password" name="password_confirmation" placeholder="Type your password again" minlength="8" required></label><?php endif; ?>
            <?php if ($page === 'register'): ?><label>Confirm password<input type="password" name="password_confirmation" placeholder="Type your password again" minlength="8" required></label><fieldset><legend>I want to</legend><div class="role-options"><label><input type="radio" name="role" value="customer" checked><span><?= e(t('register_role_customer', ui_language($user ?? null))) ?></span></label><label><input type="radio" name="role" value="seller"><span><?= e(t('register_role_seller', ui_language($user ?? null))) ?></span></label></div></fieldset><div class="seller-verification-fields" data-seller-fields hidden><label>Phone number<input type="tel" name="phone" placeholder="08x-xxx-xxxx"></label><label>Date of birth<input type="date" name="birth_date" max="<?= e(date('Y-m-d')) ?>"></label><label class="auth-full">Thai ID card number<input type="text" name="id_card_number" inputmode="numeric" placeholder="1-2345-67890-12-3"></label><label class="auth-full">Thai ID card front<input type="file" name="id_card_front" accept="image/jpeg,image/png,image/webp"></label><small class="muted auth-full">Seller accounts require age 18+, Thai ID verification, and admin approval before going live.</small></div><small class="muted"><?= e(t('register_seller_note', ui_language($user ?? null))) ?></small><?php elseif ($page === 'login'): ?><div class="form-row"><label class="check-label"><input type="checkbox" name="remember"> Remember me</label><a href="?page=forgot-password">Forgot password?</a></div><?php endif; ?>
            <button class="button button-dark button-full" type="submit"><?= $isForgot ? 'Send reset link' : ($isReset ? 'Reset password' : ($page === 'login' ? 'Sign in' : 'Create account')) ?></button>
        </form>
        <?php if ($page === 'login' && demo_mode_enabled() && demo_is_installed()): ?><div class="demo-accounts"><span>Demo access · password <strong>Demo1234!</strong></span><button type="button" data-demo-email="customer@workconnect.test">Customer</button><button type="button" data-demo-email="seller@workconnect.test">Seller</button><button type="button" data-demo-email="admin@workconnect.test">Admin</button></div><?php endif; ?>
        <div class="auth-switch"><?= $isForgot || $isReset ? 'Remembered your password?' : ($page === 'login' ? "Don't have an account?" : 'Already a member?') ?> <a href="?page=<?= $isForgot || $isReset ? 'login' : ($page === 'login' ? 'register' : 'login') ?>"><?= $isForgot || $isReset ? 'Sign in' : ($page === 'login' ? 'Sign up' : 'Sign in') ?></a></div>
    </section>
    <a class="back-link" href="?page=home">← Back to home</a>
</main>
<script src="assets/js/app.js"></script></body></html>
